import { requireAuthAndSetup } from "@/lib/guards";
import { prisma } from "@/lib/prisma";
import { updateAccountAction } from "@/app/chart-of-accounts/actions";
import { Notice, PageHeader, StatCard, StatusBadge, SurfaceSection } from "@/components/workbench";

type ChartOfAccountsPageProps = {
  searchParams: Promise<{ error?: string; updated?: string }>;
};

const errorMessages: Record<string, string> = {
  "missing-account-fields": "Account name is required.",
  "account-not-found": "Account not found."
};

export default async function ChartOfAccountsPage({
  searchParams
}: ChartOfAccountsPageProps) {
  const user = await requireAuthAndSetup();
  const params = await searchParams;

  const accounts = await prisma.account.findMany({
    where: { userId: user.id },
    orderBy: [{ accountNumber: "asc" }]
  });

  const error = params.error ? errorMessages[params.error] : null;
  const showUpdated = params.updated === "1";
  const activeCount = accounts.filter((account: (typeof accounts)[number]) => account.isActive).length;
  const systemCount = accounts.filter((account: (typeof accounts)[number]) => account.isSystem).length;

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="General ledger setup"
        title="Chart of accounts"
        description="科目表页现在也统一成系统级后台的结构，突出账户总量、活动状态和批量浏览感，而不是一组零散表单。"
      />

      {error ? <Notice variant="danger">{error}</Notice> : null}
      {showUpdated ? <Notice variant="success">Account updated successfully.</Notice> : null}

      <div className="grid gap-4 md:grid-cols-3">
        <StatCard label="Total accounts" value={String(accounts.length)} hint="Accounts generated by setup and later adjustments." />
        <StatCard label="Active accounts" value={String(activeCount)} hint="Available for document entry and posting." tone="positive" />
        <StatCard label="System accounts" value={String(systemCount)} hint="Core control accounts seeded by the setup wizard." />
      </div>

      {accounts.length === 0 ? (
        <Notice variant="warning">No accounts found. Complete setup wizard first.</Notice>
      ) : (
        <SurfaceSection
          title="Ledger accounts"
          description="Basic editing remains limited to account name and active status, preserving system structure while allowing operational cleanup."
        >
          <div className="space-y-3">
            {accounts.map((account: (typeof accounts)[number]) => (
              <form
                key={account.id}
                action={updateAccountAction}
                className="grid gap-4 rounded-[24px] border border-[var(--line)] bg-[var(--panel-soft)] p-4 xl:grid-cols-[120px_minmax(0,1.4fr)_180px_220px_160px]"
              >
                <input type="hidden" name="accountId" value={account.id} />
                <div>
                  <p className="field-label">Account no.</p>
                  <p className="text-sm font-semibold text-slate-950">{account.accountNumber}</p>
                </div>
                <div>
                  <label className="field-label" htmlFor={`name-${account.id}`}>
                    Account name
                  </label>
                  <input
                    id={`name-${account.id}`}
                    name="accountName"
                    type="text"
                    defaultValue={account.accountName}
                    className="field-input"
                    required
                  />
                </div>
                <div>
                  <p className="field-label">Type</p>
                  <p className="text-sm text-slate-700">{account.accountType}</p>
                </div>
                <div>
                  <p className="field-label">Report category</p>
                  <p className="text-sm text-slate-700">{account.reportCategory}</p>
                </div>
                <div className="flex items-end justify-between gap-3">
                  <label className="flex items-center gap-2 pb-3 text-sm text-slate-700">
                    <input
                      type="checkbox"
                      name="isActive"
                      defaultChecked={account.isActive}
                      className="h-4 w-4 rounded border-[var(--line)] text-[var(--accent)]"
                    />
                    Active
                  </label>
                  <div className="flex items-center gap-3">
                    <StatusBadge status={account.isSystem ? "system" : "custom"} />
                    <button type="submit" className="btn-primary">
                      Save
                    </button>
                  </div>
                </div>
              </form>
            ))}
          </div>
        </SurfaceSection>
      )}
    </div>
  );
}
