// <auto-generated>
//   Generated by backend/frontend/scripts/sync-tabler-icons.mjs
// </auto-generated>
using System.Collections.Generic;

namespace Citus.Ui.Shared.Icons;

public static class IconNameMap
{
    public static readonly IReadOnlyDictionary<IconName, string> SpriteIds = new Dictionary<IconName, string>
    {
        { IconName.Activity, "ti-activity" },
        { IconName.AlertCircle, "ti-alert-circle" },
        { IconName.AlertTriangle, "ti-alert-triangle" },
        { IconName.ArrowLeft, "ti-arrow-left" },
        { IconName.ArrowRight, "ti-arrow-right" },
        { IconName.Book, "ti-book" },
        { IconName.Briefcase, "ti-briefcase" },
        { IconName.Building, "ti-building" },
        { IconName.BuildingBank, "ti-building-bank" },
        { IconName.BuildingSkyscraper, "ti-building-skyscraper" },
        { IconName.BuildingStore, "ti-building-store" },
        { IconName.Calendar, "ti-calendar" },
        { IconName.Cash, "ti-cash" },
        { IconName.Check, "ti-check" },
        { IconName.ChevronDown, "ti-chevron-down" },
        { IconName.ChevronLeft, "ti-chevron-left" },
        { IconName.ChevronRight, "ti-chevron-right" },
        { IconName.ChevronUp, "ti-chevron-up" },
        { IconName.CircleCheck, "ti-circle-check" },
        { IconName.CirclePlus, "ti-circle-plus" },
        { IconName.Clock, "ti-clock" },
        { IconName.Coin, "ti-coin" },
        { IconName.Dashboard, "ti-dashboard" },
        { IconName.Database, "ti-database" },
        { IconName.DeviceDesktop, "ti-device-desktop" },
        { IconName.Dots, "ti-dots" },
        { IconName.Download, "ti-download" },
        { IconName.Eye, "ti-eye" },
        { IconName.File, "ti-file" },
        { IconName.FileInvoice, "ti-file-invoice" },
        { IconName.FileText, "ti-file-text" },
        { IconName.Filter, "ti-filter" },
        { IconName.Home, "ti-home" },
        { IconName.InfoCircle, "ti-info-circle" },
        { IconName.LayoutDashboard, "ti-layout-dashboard" },
        { IconName.Logout, "ti-logout" },
        { IconName.Menu2, "ti-menu-2" },
        { IconName.Moon, "ti-moon" },
        { IconName.Pencil, "ti-pencil" },
        { IconName.Plus, "ti-plus" },
        { IconName.Puzzle, "ti-puzzle" },
        { IconName.Receipt, "ti-receipt" },
        { IconName.Refresh, "ti-refresh" },
        { IconName.Report, "ti-report" },
        { IconName.ReportAnalytics, "ti-report-analytics" },
        { IconName.Search, "ti-search" },
        { IconName.Settings, "ti-settings" },
        { IconName.ShieldLock, "ti-shield-lock" },
        { IconName.Sun, "ti-sun" },
        { IconName.Tool, "ti-tool" },
        { IconName.Trash, "ti-trash" },
        { IconName.Truck, "ti-truck" },
        { IconName.User, "ti-user" },
        { IconName.Users, "ti-users" },
        { IconName.Wallet, "ti-wallet" },
        { IconName.World, "ti-world" },
        { IconName.X, "ti-x" }
    };
}
