// <auto-generated>
//   Generated by backend/frontend/scripts/sync-tabler-icons.mjs
//   Do not edit by hand — update the allowlist and re-run `pnpm run icons:sync`.
// </auto-generated>
namespace Citus.Ui.Shared.Icons;

/// <summary>
/// Strongly-typed Tabler icon names available in tabler-sprite.svg.
/// </summary>
public enum IconName
{
        AlertCircle,
        AlertTriangle,
        ArrowLeft,
        ArrowRight,
        Building,
        BuildingBank,
        Calendar,
        Cash,
        Check,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        ChevronUp,
        CircleCheck,
        Clock,
        Coin,
        Dashboard,
        Dots,
        Download,
        Eye,
        File,
        FileInvoice,
        FileText,
        Filter,
        Home,
        InfoCircle,
        Logout,
        Menu2,
        Moon,
        Pencil,
        Plus,
        Receipt,
        Refresh,
        Report,
        Search,
        Settings,
        ShieldLock,
        Sun,
        Trash,
        User,
        Users,
        Wallet,
        World,
        X,
}
